"""Adicionar comprovante_arquivo em venda_pagamentos

Revision ID: 0940bd462679
Revises: 4d1b14ecfd60
Create Date: 2026-08-04 07:27:00.383355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0940bd462679'
down_revision = '4d1b14ecfd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprovante_arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_pagamentos', schema=None) as batch_op:
        batch_op.drop_column('comprovante_arquivo')

    # ### end Alembic commands ###
